engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
    - src/**/*.js
exclude_paths:
  - src/**/*.spec.js
ecmaFeatures:
  modules: true
  jsx: true
env:
  browser: true
  es6: true
  node: true
